window.GIFT_PRODUCTS = [
  { id: 1, name: "Classic White Dress Shirt", category: "clothes", price: 1299, oldPrice: 1799, badge: "Sale", emoji: "👔", gradient: "linear-gradient(135deg,#f8fafc,#e2e8f0)" },
  { id: 2, name: "Floral Summer Midi Dress", category: "clothes", price: 1899, oldPrice: 0, badge: null, emoji: "👗", gradient: "linear-gradient(135deg,#fce7f3,#fbcfe8)" },
  { id: 3, name: "Kids' Cotton Hoodie Set", category: "clothes", price: 999, oldPrice: 1299, badge: "Sale", emoji: "🧥", gradient: "linear-gradient(135deg,#fef3c7,#fde68a)" },
  { id: 4, name: "Saree Gift Pack - Premium Silk", category: "clothes", price: 3499, oldPrice: 0, badge: "Premium", emoji: "🪡", gradient: "linear-gradient(135deg,#ede9fe,#ddd6fe)" },
  { id: 5, name: "Cuddly Teddy Bear - 40cm", category: "toys", price: 799, oldPrice: 999, badge: "Bestseller", emoji: "🧸", gradient: "linear-gradient(135deg,#fef9c3,#fef08a)" },
  { id: 6, name: "STEM Building Blocks Set", category: "toys", price: 1499, oldPrice: 0, badge: null, emoji: "🧱", gradient: "linear-gradient(135deg,#cffafe,#a5f3fc)" },
  { id: 7, name: "Remote Control Racing Car", category: "toys", price: 1249, oldPrice: 1599, badge: "Sale", emoji: "🚗", gradient: "linear-gradient(135deg,#fee2e2,#fecaca)" },
  { id: 8, name: "Baby Doll Gift Set", category: "toys", price: 999, oldPrice: 0, badge: null, emoji: "🎎", gradient: "linear-gradient(135deg,#fce7f3,#f5d0fe)" },
  { id: 9, name: "Fresh Red Rose Bouquet", category: "flowers", price: 899, oldPrice: 1099, badge: "Bestseller", emoji: "🌹", gradient: "linear-gradient(135deg,#ffd1d1,#fda4af)" },
  { id: 10, name: "Sunflower Bunch - 12 Stems", category: "flowers", price: 749, oldPrice: 0, badge: null, emoji: "🌻", gradient: "linear-gradient(135deg,#fef3c7,#fcd34d)" },
  { id: 11, name: "Mixed Tulip Hand-Tied Bouquet", category: "flowers", price: 1299, oldPrice: 0, badge: "Premium", emoji: "🌷", gradient: "linear-gradient(135deg,#fbcfe8,#f9a8d4)" },
  { id: 12, name: "Orchid Planter in Ceramic Pot", category: "flowers", price: 1599, oldPrice: 1899, badge: "Sale", emoji: "🪷", gradient: "linear-gradient(135deg,#ddd6fe,#c4b5fd)" },
  { id: 13, name: "Chocolate Truffle Cake - 1kg", category: "cakes", price: 999, oldPrice: 0, badge: "Bestseller", emoji: "🍫", gradient: "linear-gradient(135deg,#e7d8c9,#d6c0a9)" },
  { id: 14, name: "Classic Vanilla Birthday Cake", category: "cakes", price: 849, oldPrice: 1049, badge: "Sale", emoji: "🍰", gradient: "linear-gradient(135deg,#ffe4e6,#fecdd3)" },
  { id: 15, name: "Red Velvet Celebration Cake - 1kg", category: "cakes", price: 1149, oldPrice: 0, badge: null, emoji: "🍒", gradient: "linear-gradient(135deg,#fecaca,#f87171)" },
  { id: 16, name: "Strawberry Cream Cake - 1kg", category: "cakes", price: 1099, oldPrice: 0, badge: "Premium", emoji: "🍓", gradient: "linear-gradient(135deg,#fce7f3,#fda4af)" },
  { id: 17, name: "Giant Teddy Bear - 60cm", category: "teddy", price: 1499, oldPrice: 1999, badge: "Bestseller", emoji: "🧸", gradient: "linear-gradient(135deg,#fef3c7,#fcd34d)" },
  { id: 18, name: "Huggable Teddy Bear - 40cm", category: "teddy", price: 999, oldPrice: 0, badge: null, emoji: "🐻", gradient: "linear-gradient(135deg,#fef9c3,#fde68a)" },
  { id: 19, name: "Teddy Bear Gift Basket", category: "teddy", price: 1799, oldPrice: 0, badge: "Premium", emoji: "🎁", gradient: "linear-gradient(135deg,#fce7f3,#f9a8d4)" },
  { id: 20, name: "Heart Teddy Bear with Card", category: "teddy", price: 1199, oldPrice: 1399, badge: "Sale", emoji: "🧸", gradient: "linear-gradient(135deg,#ffd1d1,#fda4af)" },
  { id: 21, name: "Classic White Sneakers", category: "shoes", price: 1499, oldPrice: 1999, badge: "Sale", emoji: "👟", gradient: "linear-gradient(135deg,#f8fafc,#e2e8f0)" },
  { id: 22, name: "Sports Running Shoes", category: "shoes", price: 2499, oldPrice: 0, badge: "Bestseller", emoji: "👟", gradient: "linear-gradient(135deg,#dcfce7,#bbf7d0)" },
  { id: 23, name: "Kids' Summer Sandals", category: "shoes", price: 799, oldPrice: 0, badge: null, emoji: "🩴", gradient: "linear-gradient(135deg,#fef3c7,#fde68a)" },
  { id: 24, name: "Formal Leather Shoes", category: "shoes", price: 3299, oldPrice: 0, badge: "Premium", emoji: "👞", gradient: "linear-gradient(135deg,#e7d8c9,#d6c0a9)" },
  { id: 25, name: "Money Plant in Ceramic Pot", category: "plants", price: 499, oldPrice: 0, badge: "Bestseller", emoji: "🪴", gradient: "linear-gradient(135deg,#dcfce7,#86efac)" },
  { id: 26, name: "Lucky Bamboo Plant", category: "plants", price: 649, oldPrice: 799, badge: "Sale", emoji: "🎋", gradient: "linear-gradient(135deg,#ccfbf1,#5eead4)" },
  { id: 27, name: "Snake Plant in Decor Pot", category: "plants", price: 899, oldPrice: 0, badge: null, emoji: "🌿", gradient: "linear-gradient(135deg,#d9f99d,#a3e635)" },
  { id: 28, name: "Peace Lily in Bloom Pot", category: "plants", price: 1199, oldPrice: 0, badge: "Premium", emoji: "🌱", gradient: "linear-gradient(135deg,#bbf7d0,#4ade80)" },
  { id: 29, name: "Cake + Flowers Combo", category: "combo", price: 1899, oldPrice: 2199, badge: "Sale", emoji: "🎂", gradient: "linear-gradient(135deg,#fce7f3,#f9a8d4)" },
  { id: 30, name: "Teddy + Chocolates Combo", category: "combo", price: 1499, oldPrice: 0, badge: "Bestseller", emoji: "🧸", gradient: "linear-gradient(135deg,#fef9c3,#fde68a)" },
  { id: 31, name: "Perfume + Flowers Combo", category: "combo", price: 2499, oldPrice: 2999, badge: "Sale", emoji: "🌸", gradient: "linear-gradient(135deg,#fbcfe8,#c4b5fd)" },
  { id: 32, name: "Birthday Surprise Box", category: "combo", price: 1999, oldPrice: 0, badge: "Premium", emoji: "🎉", gradient: "linear-gradient(135deg,#ddd6fe,#f9a8d4)" },
  { id: 33, name: "Classic Aviator Sunglasses", category: "sunglasses", price: 1299, oldPrice: 1699, badge: "Sale", emoji: "🕶️", gradient: "linear-gradient(135deg,#e2e8f0,#cbd5e1)" },
  { id: 34, name: "Polarized Wayfarer Sunglasses", category: "sunglasses", price: 1499, oldPrice: 0, badge: "Bestseller", emoji: "🕶️", gradient: "linear-gradient(135deg,#fef3c7,#fde68a)" },
  { id: 35, name: "Round Retro Sunglasses", category: "sunglasses", price: 1099, oldPrice: 0, badge: null, emoji: "🕶️", gradient: "linear-gradient(135deg,#fce7f3,#f5d0fe)" },
  { id: 36, name: "Sports UV Sunglasses", category: "sunglasses", price: 999, oldPrice: 1299, badge: "Sale", emoji: "🕶️", gradient: "linear-gradient(135deg,#cffafe,#a5f3fc)" },
  { id: 37, name: "Classic Baseball Cap", category: "caps", price: 499, oldPrice: 0, badge: null, emoji: "🧢", gradient: "linear-gradient(135deg,#e2e8f0,#cbd5e1)" },
  { id: 38, name: "Embroidered Snapback Cap", category: "caps", price: 699, oldPrice: 899, badge: "Bestseller", emoji: "🧢", gradient: "linear-gradient(135deg,#fbcfe8,#f9a8d4)" },
  { id: 39, name: "Summer Bucket Hat", category: "caps", price: 549, oldPrice: 0, badge: null, emoji: "👒", gradient: "linear-gradient(135deg,#fef3c7,#fcd34d)" },
  { id: 40, name: "Woolen Winter Beanie", category: "caps", price: 649, oldPrice: 799, badge: "Sale", emoji: "🧣", gradient: "linear-gradient(135deg,#ddd6fe,#c4b5fd)" },
  { id: 41, name: "Leather Belt - Brown", category: "belts", price: 799, oldPrice: 0, badge: "Bestseller", emoji: "🪢", gradient: "linear-gradient(135deg,#e7d8c9,#d6c0a9)" },
  { id: 42, name: "Formal Black Belt", category: "belts", price: 699, oldPrice: 899, badge: "Sale", emoji: "🖤", gradient: "linear-gradient(135deg,#334155,#1e293b)" },
  { id: 43, name: "Casual Canvas Belt", category: "belts", price: 449, oldPrice: 0, badge: null, emoji: "🪢", gradient: "linear-gradient(135deg,#d9f99d,#a3e635)" },
  { id: 44, name: "Premium Reversible Belt", category: "belts", price: 1199, oldPrice: 0, badge: "Premium", emoji: "✨", gradient: "linear-gradient(135deg,#fef9c3,#fde68a)" }
];
