services:
  - type: web
    name: giftora
    runtime: node
    repo: https://github.com/Amit1296/giftora
    branch: master
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
